# Makefile
# Author: bajackson1@quinniac.edu

all: add_hamming remove_hamming check_hamming

add_hamming: add_hamming.c
	gcc -Wall -o add_hamming add_hamming.c

remove_hamming: remove_hamming.c
	gcc -Wall -o remove_hamming remove_hamming.c

check_hamming: check_hamming.c
	gcc -Wall -o check_hamming check_hamming.c

clean:
	rm -f add_hamming remove_hamming check_hamming